/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package master;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import koneksi.koneksi;

/**
 *
 * @author DafaAbdr
 */
public class dataLayanan extends javax.swing.JPanel {

    /**
     * Creates new form dataLayanan
     */
    public dataLayanan() {
        initComponents();
        tIDLayanan.setEditable(false);
        tIDLayanan.setEnabled(false);
        tampilData();
        bersih();
        idOtomatis();
    }

    private void bersih() {
        tNamaLayanan.setText("");
        tHarga.setText("");
        tableLayanan.clearSelection();
        idOtomatis();
        tNamaLayanan.requestFocus();
    }

    private void idOtomatis() {
        try {
            Connection conn = koneksi.getConnection();

            String sql = "SELECT id FROM datalayanan ORDER BY id DESC LIMIT 1";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                String id = rs.getString("id").substring(1);
                int no = Integer.parseInt(id) + 1;

                tIDLayanan.setText(String.format("L%03d", no));
            } else {
                tIDLayanan.setText("L001");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    public void tampilData() {
        DefaultTableModel model = new DefaultTableModel();
        NumberFormat rupiah = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
        
        model.addColumn("ID");
        model.addColumn("Nama Layanan");
        model.addColumn("Harga");

        try {
            Connection conn = koneksi.getConnection();
            String sql = "SELECT * FROM datalayanan ORDER BY id";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id"),
                    rs.getString("nama_layanan"),
                    rupiah.format(rs.getLong("harga")).replace(",00","")
                });
            }

            tableLayanan.setModel(model);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tIDLayanan = new javax.swing.JTextField();
        tNamaLayanan = new javax.swing.JTextField();
        tHarga = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLayanan = new javax.swing.JTable();
        bBersihkan = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bTambah = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(750, 560));
        setMinimumSize(new java.awt.Dimension(750, 560));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 51));
        jLabel1.setText("| Data Layanan");

        jLabel2.setText("ID Layanan:");

        tIDLayanan.setEditable(false);

        jLabel3.setText("Nama Layanan");

        jLabel4.setText("Harga");

        tableLayanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableLayanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLayananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableLayanan);

        bBersihkan.setBackground(new java.awt.Color(102, 0, 51));
        bBersihkan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bBersihkan.setForeground(new java.awt.Color(255, 255, 255));
        bBersihkan.setText("Bersihkan");
        bBersihkan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBersihkanActionPerformed(evt);
            }
        });

        bHapus.setBackground(new java.awt.Color(102, 0, 51));
        bHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bHapus.setForeground(new java.awt.Color(255, 255, 255));
        bHapus.setText("Hapus");
        bHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bUbah.setBackground(new java.awt.Color(102, 0, 51));
        bUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bUbah.setForeground(new java.awt.Color(255, 255, 255));
        bUbah.setText("Ubah");
        bUbah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        bTambah.setBackground(new java.awt.Color(102, 0, 51));
        bTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bTambah.setForeground(new java.awt.Color(255, 255, 255));
        bTambah.setText("Tambah");
        bTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tIDLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tNamaLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(bBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tIDLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNamaLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBersihkan)
                    .addComponent(bHapus)
                    .addComponent(bUbah)
                    .addComponent(bTambah))
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        if (tIDLayanan.getText().isEmpty() ||
        tNamaLayanan.getText().isEmpty() ||
        tHarga.getText().isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(this, "Lengkapi data terlebih dahulu!");
            return;
        }

        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Apakah Anda yakin ingin mengubah data ini?",
                "Konfirmasi Ubah",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            try {
                Connection conn = koneksi.getConnection();

                String sql = "UPDATE datalayanan SET nama_layanan=?, harga=? WHERE id=?";
                PreparedStatement pst = conn.prepareStatement(sql);

                pst.setString(1, tNamaLayanan.getText());
                pst.setLong(2, Long.parseLong(tHarga.getText()));
                pst.setString(3, tIDLayanan.getText());

                pst.executeUpdate();

                javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil diubah.");

                tampilData();
                bersih();

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengubah data!\n" + e.getMessage());
            }
        }
    }//GEN-LAST:event_bUbahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        if (tIDLayanan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus!");
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(
                this,
                "Apakah Anda yakin ingin menghapus data ini?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                Connection conn = koneksi.getConnection();

                String sql = "DELETE FROM datalayanan WHERE id = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, tIDLayanan.getText());

                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");

                tampilData();
                bersih();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data!\n" + e.getMessage());
            }
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void tableLayananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLayananMouseClicked
        int baris = tableLayanan.getSelectedRow();

        tIDLayanan.setText(tableLayanan.getValueAt(baris, 0).toString());
        tNamaLayanan.setText(tableLayanan.getValueAt(baris, 1).toString());

        String harga = tableLayanan.getValueAt(baris, 2).toString();
        harga = harga.replace("Rp.", "")
                     .replace("Rp", "")
                     .replace(".", "")
                     .replace(",", "")
                     .trim();

        tHarga.setText(harga);
    }//GEN-LAST:event_tableLayananMouseClicked

    private void bBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBersihkanActionPerformed
        bersih();
    }//GEN-LAST:event_bBersihkanActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        if (tIDLayanan.getText().isEmpty() ||
        tNamaLayanan.getText().isEmpty() ||
        tHarga.getText().isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(this, "Lengkapi semua data terlebih dahulu!");
        return;
    }

    try {
        Connection conn = koneksi.getConnection();

        String sql = "INSERT INTO datalayanan (id, nama_layanan, harga) VALUES (?, ?, ?)";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, tIDLayanan.getText());
        pst.setString(2, tNamaLayanan.getText());
        pst.setLong(3, Long.parseLong(tHarga.getText()));

        pst.executeUpdate();

        javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan.");

        tampilData();
        bersih();
        idOtomatis();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal menambahkan data!\n" + e.getMessage());
    }
    }//GEN-LAST:event_bTambahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBersihkan;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tHarga;
    private javax.swing.JTextField tIDLayanan;
    private javax.swing.JTextField tNamaLayanan;
    private javax.swing.JTable tableLayanan;
    // End of variables declaration//GEN-END:variables
}
