/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package master;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author DafaAbdr
 */

public class dataTransaksi extends javax.swing.JPanel {

    /**
     * Creates new form dataTransaksi
     */
    public dataTransaksi() {
        initComponents();
        tHarga.setEditable(false);
        tIDTransaksi.setEditable(false);
        tIDTransaksi.setEnabled(false);
        idTransaksiOtomatis();
        tampilComboLayanan();
        tampilDetailTransaksi();
        bersih();
    }
    
    private void bersih() {
        tNamaLayanan.setSelectedIndex(-1);
        tHarga.setText("");
        tTanggal.setDate(null);
    }

    private void idTransaksiOtomatis() {
        try {
            Connection conn = koneksi.getConnection();

            String sql = "SELECT id_transaksi FROM transaksi ORDER BY id_transaksi DESC LIMIT 1";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                int no = Integer.parseInt(rs.getString("id_transaksi").substring(1)) + 1;
                tIDTransaksi.setText(String.format("T%03d", no));
            } else {
                tIDTransaksi.setText("T001");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void tampilComboLayanan() {
        try {
            Connection conn = koneksi.getConnection();

            String sql = "SELECT nama_layanan FROM datalayanan ORDER BY id ASC";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            tNamaLayanan.removeAllItems();

            while (rs.next()) {
                tNamaLayanan.addItem(rs.getString("nama_layanan"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void tampilDetailTransaksi() {
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("ID Transaksi");
        model.addColumn("ID Layanan");
        model.addColumn("Nama Layanan");
        model.addColumn("Harga");

        try {

            Connection conn = koneksi.getConnection();

            String sql = "SELECT id_transaksi, id_layanan,nama_layanan,harga "
                    + "FROM detail_transaksi "
                    + "WHERE id_transaksi=?";

            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, tIDTransaksi.getText());

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {

                model.addRow(new Object[]{
                    rs.getString("id_transaksi"),
                    rs.getString("id_layanan"),
                    rs.getString("nama_layanan"),
                    rs.getLong("harga")
                });

            }

            tabelTransaksi.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tNamaLayanan = new javax.swing.JComboBox<>();
        tHarga = new javax.swing.JTextField();
        tTanggal = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bTambahkan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        bSimpan = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bBersihkan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tIDTransaksi = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 51));
        jLabel1.setText("| Data Transaksi");

        jLabel2.setText("ID Transaksi");

        tNamaLayanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tNamaLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaLayananActionPerformed(evt);
            }
        });

        tHarga.setEditable(false);

        jLabel3.setText("Nama Layanan");

        jLabel4.setText("Harga");

        bTambahkan.setBackground(new java.awt.Color(102, 0, 51));
        bTambahkan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bTambahkan.setForeground(new java.awt.Color(255, 255, 255));
        bTambahkan.setText("Tambahkan");
        bTambahkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahkanActionPerformed(evt);
            }
        });

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelTransaksi);

        bSimpan.setBackground(new java.awt.Color(102, 0, 51));
        bSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bSimpan.setForeground(new java.awt.Color(255, 255, 255));
        bSimpan.setText("Simpan");
        bSimpan.setMaximumSize(new java.awt.Dimension(74, 23));
        bSimpan.setMinimumSize(new java.awt.Dimension(74, 23));
        bSimpan.setPreferredSize(new java.awt.Dimension(74, 23));
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bUbah.setBackground(new java.awt.Color(102, 0, 51));
        bUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bUbah.setForeground(new java.awt.Color(255, 255, 255));
        bUbah.setText("Ubah");
        bUbah.setMaximumSize(new java.awt.Dimension(74, 23));
        bUbah.setMinimumSize(new java.awt.Dimension(74, 23));
        bUbah.setPreferredSize(new java.awt.Dimension(74, 23));

        bHapus.setBackground(new java.awt.Color(102, 0, 51));
        bHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bHapus.setForeground(new java.awt.Color(255, 255, 255));
        bHapus.setText("Hapus");
        bHapus.setMaximumSize(new java.awt.Dimension(74, 23));
        bHapus.setMinimumSize(new java.awt.Dimension(74, 23));
        bHapus.setPreferredSize(new java.awt.Dimension(74, 23));

        bBersihkan.setBackground(new java.awt.Color(102, 0, 51));
        bBersihkan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bBersihkan.setForeground(new java.awt.Color(255, 255, 255));
        bBersihkan.setText("Bersihkan");
        bBersihkan.setMaximumSize(new java.awt.Dimension(74, 23));
        bBersihkan.setMinimumSize(new java.awt.Dimension(74, 23));
        bBersihkan.setPreferredSize(new java.awt.Dimension(74, 23));

        jLabel5.setText("Tanggal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(tIDTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tNamaLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(tTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bTambahkan, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(bUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(bSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNamaLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tIDTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bTambahkan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tNamaLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaLayananActionPerformed
        if (tNamaLayanan.getSelectedItem() == null) {
            return;
        }

        try {
            Connection conn = koneksi.getConnection();

            String sql = "SELECT harga FROM datalayanan WHERE nama_layanan = ?";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, tNamaLayanan.getSelectedItem().toString());

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                tHarga.setText(rs.getString("harga"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_tNamaLayananActionPerformed

    private void bTambahkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahkanActionPerformed
        if (tIDTransaksi.getText().isEmpty()
            || tTanggal.getDate() == null
            || tNamaLayanan.getSelectedItem() == null
            || tHarga.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Lengkapi data terlebih dahulu!");
            return;
        }

        try {

            Connection conn = koneksi.getConnection();

            // Ambil ID Layanan
            String idLayanan = "";

            String sqlLayanan = "SELECT id FROM datalayanan WHERE nama_layanan=?";
            PreparedStatement psLayanan = conn.prepareStatement(sqlLayanan);
            psLayanan.setString(1, tNamaLayanan.getSelectedItem().toString());

            ResultSet rs = psLayanan.executeQuery();

            if (rs.next()) {
                idLayanan = rs.getString("id");
            }

            // Simpan ke detail_transaksi
            String sql = "INSERT INTO detail_transaksi "
                    + "(id_transaksi,id_layanan,nama_layanan,harga) "
                    + "VALUES (?,?,?,?)";

            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, tIDTransaksi.getText());
            pst.setString(2, idLayanan);
            pst.setString(3, tNamaLayanan.getSelectedItem().toString());
            pst.setLong(4, Long.parseLong(tHarga.getText()));

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Layanan berhasil ditambahkan.");

            tampilDetailTransaksi();

            tNamaLayanan.setSelectedIndex(-1);
            tHarga.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_bTambahkanActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        if (tIDTransaksi.getText().isEmpty() || tTanggal.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Lengkapi ID Transaksi dan Tanggal!");
        return;
        }

        try {

            Connection conn = koneksi.getConnection();

            String cek = "SELECT COUNT(*) AS jumlah, SUM(harga) AS total "
                       + "FROM detail_transaksi WHERE id_transaksi=?";

            PreparedStatement pstCek = conn.prepareStatement(cek);
            pstCek.setString(1, tIDTransaksi.getText());

            ResultSet rs = pstCek.executeQuery();

            int jumlah = 0;
            long total = 0;

            if (rs.next()) {
                jumlah = rs.getInt("jumlah");
                total = rs.getLong("total");
            }

            if (jumlah == 0) {
                JOptionPane.showMessageDialog(this, "Belum ada layanan yang ditambahkan!");
                return;
            }

            String sql = "INSERT INTO transaksi(id_transaksi,tanggal,total_harga) VALUES(?,?,?)";

            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, tIDTransaksi.getText());

            java.sql.Date tanggal = new java.sql.Date(tTanggal.getDate().getTime());

            pst.setDate(2, tanggal);
            pst.setLong(3, total);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Transaksi berhasil disimpan.");

            DefaultTableModel model = (DefaultTableModel) tabelTransaksi.getModel();
            model.setRowCount(0);

            bersih();

            idTransaksiOtomatis();
            tampilDetailTransaksi();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_bSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBersihkan;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bTambahkan;
    private javax.swing.JButton bUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tHarga;
    private javax.swing.JTextField tIDTransaksi;
    private javax.swing.JComboBox<String> tNamaLayanan;
    private com.toedter.calendar.JDateChooser tTanggal;
    private javax.swing.JTable tabelTransaksi;
    // End of variables declaration//GEN-END:variables
}
