/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package master;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import popUp.laporanDataTransaksi;
import java.io.InputStream;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import login.session;
/**
 *
 * @author DafaAbdr
 */
public class laporan extends javax.swing.JPanel {

    /**
     * Creates new form laporan
     */
    public laporan() {
        initComponents();
        tampilDataHasilAsosiasi();
    }

    private void tampilDataHasilAsosiasi() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Proses");
        model.addColumn("Tanggal Proses");
        model.addColumn("Mulai Tanggal");
        model.addColumn("Sampai Tanggal");
        model.addColumn("Min Support (%)");
        model.addColumn("Min Confidence (%)");
        try {
            Connection conn = koneksi.getConnection();

            String sql = "SELECT * FROM hasil_asosiasi ORDER BY id DESC";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id"),
                    rs.getDate("tanggal_proses"),
                    rs.getDate("mulai_tanggal"),
                    rs.getDate("sampai_tanggal"),
                    rs.getDouble("min_support"),
                    rs.getDouble("min_confidence")
                });
            }
            tableProses.setModel(model);
            rs.close();
            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bDataLayanan = new javax.swing.JButton();
        bDataTransaksi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProses = new javax.swing.JTable();
        tIDProses = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bCetak = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 51));
        jLabel1.setText("| Laporan");

        bDataLayanan.setBackground(new java.awt.Color(102, 0, 51));
        bDataLayanan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bDataLayanan.setForeground(new java.awt.Color(255, 255, 255));
        bDataLayanan.setText("Data Layanan");
        bDataLayanan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bDataLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDataLayananActionPerformed(evt);
            }
        });

        bDataTransaksi.setBackground(new java.awt.Color(102, 0, 51));
        bDataTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bDataTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        bDataTransaksi.setText("Data Transaksi");
        bDataTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bDataTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDataTransaksiActionPerformed(evt);
            }
        });

        tableProses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableProses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProsesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProses);

        tIDProses.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ID Proses");

        bCetak.setBackground(new java.awt.Color(102, 0, 51));
        bCetak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bCetak.setForeground(new java.awt.Color(255, 255, 255));
        bCetak.setText("Cetak");
        bCetak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCetakActionPerformed(evt);
            }
        });

        bHapus.setBackground(new java.awt.Color(102, 0, 51));
        bHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bHapus.setForeground(new java.awt.Color(255, 255, 255));
        bHapus.setText("Hapus");
        bHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(bDataLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bDataTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tIDProses, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(145, 145, 145)
                                .addComponent(bCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bDataLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDataTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tIDProses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bCetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bDataTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDataTransaksiActionPerformed
        laporanDataTransaksi ldt = new laporanDataTransaksi();
        ldt.setLocationRelativeTo(this);
        ldt.setVisible(true);
    }//GEN-LAST:event_bDataTransaksiActionPerformed

    private void tableProsesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProsesMouseClicked
        int baris = tableProses.getSelectedRow();

        tIDProses.setText(
            tableProses.getValueAt(baris, 0).toString()
        );
    }//GEN-LAST:event_tableProsesMouseClicked

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        String id = tIDProses.getText().trim();
            if (id.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Pilih terlebih dahulu ID Proses yang akan dihapus.");
                return;
            }
            int konfirmasi = JOptionPane.showConfirmDialog(
                    this,
                    "Yakin ingin menghapus data dengan ID " + id + " ?",
                    "Konfirmasi",
                    JOptionPane.YES_NO_OPTION);
            if (konfirmasi == JOptionPane.YES_OPTION) {
                try {
                    Connection conn = koneksi.getConnection();

                    String sql = "DELETE FROM hasil_asosiasi WHERE id=?";
                    PreparedStatement pst = conn.prepareStatement(sql);
                    pst.setString(1, id);

                    int hasil = pst.executeUpdate();
                    if (hasil > 0) {
                        JOptionPane.showMessageDialog(this,
                                "Data berhasil dihapus.");
                        tIDProses.setText("");
                        tampilDataHasilAsosiasi();
                    } else {
                        JOptionPane.showMessageDialog(this,
                                "Data tidak ditemukan.");
                    }
                    pst.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bDataLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDataLayananActionPerformed
        try {

            Connection conn = koneksi.getConnection();

            HashMap<String, Object> parameter = new HashMap<>();

            parameter.put("NAMA_ADMIN", session.namaLengkap);
            
            parameter.put(
                "LOGO",
                getClass().getResourceAsStream("/gambar/logo.png")
            );
            

            InputStream report = getClass().getResourceAsStream("/laporan/dataLayanan.jasper");

            JasperPrint jp = JasperFillManager.fillReport(report, parameter, conn);

            JasperViewer.viewReport(jp, false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_bDataLayananActionPerformed

    private void bCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCetakActionPerformed
        try {

            Connection conn = koneksi.getConnection();

            HashMap<String, Object> parameter = new HashMap<>();

            parameter.put("NAMA_ADMIN", session.namaLengkap);
            parameter.put("ID_PROSES", tIDProses.getText());

            parameter.put(
                "LOGO",
                getClass().getResourceAsStream("/gambar/logo.png")
            );

            InputStream report = getClass().getResourceAsStream("/laporan/dataProses.jasper");

            JasperPrint jp = JasperFillManager.fillReport(report, parameter, conn);

            JasperViewer.viewReport(jp, false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_bCetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCetak;
    private javax.swing.JButton bDataLayanan;
    private javax.swing.JButton bDataTransaksi;
    private javax.swing.JButton bHapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tIDProses;
    private javax.swing.JTable tableProses;
    // End of variables declaration//GEN-END:variables
}
